# Generated by Django 3.2.9 on 2021-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211108_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
